### ISSUE TITLE
Allow "*" for CORS

### ISSUE THREAD

**Issue by muttcg** [gbif/registry-spring-boot#11]
Response works -> https://api.gbif-dev.org/v1/organization?limit=0 , but because of CORS, portal fails

Access to XMLHttpRequest at 'https://api.gbif-dev.org/v1/dataset/search?limit=0' from origin 'https://www.gbif-dev.org' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.

(index):1 Access to XMLHttpRequest at 'https://api.gbif-dev.org/v1/organization?limit=0' from origin 'https://www.gbif-dev.org' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.

(index):1 Access to XMLHttpRequest at 'https://api.gbif-dev.org/v1/organization/nonPublishing?limit=0' from origin 'https://www.gbif-dev.org' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.

**Comment by mike-podolskiy90** [comment]
Fixed

**Comment by marcos-lg** [comment]
Looks like it's still happening. When the page loads for the first time it shows the CORS error, but if you refresh the page it works.

**Comment by marcos-lg** [comment]
Fixed in DEV
